version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_server
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/setupDb.sql:/docker-entrypoint-initdb.d/init.sql # Mounts your SQL file to initialize the DB

volumes:
  postgres_data:
